name: MyFirstJob

on: [push]

jobs:
  Docker_images:
    runs-on: ubuntu-latest
    name: Docker Images and Container view
    #defaults:
     # run:
       # working-directory: /home/runner/work/GitHubactions-1/GitHubactions-1/./github/github/workflows
    steps:
      - uses: actions/checkout@v1
      - name: Docker Image Build
        #working-directory: githubfiles
        run: docker build . --file Dockerfile --tag my-image1:$(date +%s)
      - name: Docker run containers
        run: docker run -d 8080:8080 my-image1
      - name: Get the output docker image
        run: docker images
      - name: Get the output docker containers
        run: docker ps -a
