name: MyFirstJob

on: [push]

jobs:
  Docker_images:
    runs-on: ubuntu-latest
    name: Docker Images and Container view
    #defaults:
     # run:
       # working-directory: /home/runner/work/GitHubactions-1/GitHubactions-1/./github/github/workflows
    steps:
      - uses: actions/checkout@v1
      - name: Docker Image Build
        #working-directory: githubfiles
        run: docker build . --file Dockerfile --tag my-image1
      - name: Docker run containers
        run: docker run -d my-image1 8080:8080
      - name: Get the output docker image
        run: docker images
      - name: Get the output docker containers
        run: docker container ls
        run: docker container commit 70a9796a2ebd rhel-httpd:latest
